# Boolean Indexing

In [1]:
import numpy as np

In [25]:
name = np.array (['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [26]:
data = np.random.randn(7,4)

In [27]:
data

array([[ 0.11792867,  0.5669166 , -0.37619867, -0.71531847],
       [ 0.35090495,  0.58773874,  1.08992674,  0.88586228],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.33188533, -1.63265133,  0.01618467, -0.83990496],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [-1.41529408, -0.71560577,  1.2651924 , -0.94210196],
       [-1.96300764,  0.70733253,  0.71089796, -0.30648372]])

In [28]:
name == 'Bob'

array([ True, False, False,  True, False, False, False])

In [29]:
data[name == 'Bob']

array([[ 0.11792867,  0.5669166 , -0.37619867, -0.71531847],
       [ 0.33188533, -1.63265133,  0.01618467, -0.83990496]])

In [30]:
data[name!='Bob']

array([[ 0.35090495,  0.58773874,  1.08992674,  0.88586228],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [-1.41529408, -0.71560577,  1.2651924 , -0.94210196],
       [-1.96300764,  0.70733253,  0.71089796, -0.30648372]])

In [31]:
name !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [32]:
data[name=='Bob', 2:]

array([[-0.37619867, -0.71531847],
       [ 0.01618467, -0.83990496]])

In [33]:
data

array([[ 0.11792867,  0.5669166 , -0.37619867, -0.71531847],
       [ 0.35090495,  0.58773874,  1.08992674,  0.88586228],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.33188533, -1.63265133,  0.01618467, -0.83990496],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [-1.41529408, -0.71560577,  1.2651924 , -0.94210196],
       [-1.96300764,  0.70733253,  0.71089796, -0.30648372]])

In [39]:
data[3]

array([ 0.33188533, -1.63265133,  0.01618467, -0.83990496])

In [36]:
data[[3,4,0,1]]

array([[ 0.33188533, -1.63265133,  0.01618467, -0.83990496],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [ 0.11792867,  0.5669166 , -0.37619867, -0.71531847],
       [ 0.35090495,  0.58773874,  1.08992674,  0.88586228]])

In [41]:
data[~(name == 'Bob')]

array([[ 0.35090495,  0.58773874,  1.08992674,  0.88586228],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [-1.41529408, -0.71560577,  1.2651924 , -0.94210196],
       [-1.96300764,  0.70733253,  0.71089796, -0.30648372]])

In [43]:
cond = name =='Bob'

In [44]:
data[~cond]

array([[ 0.35090495,  0.58773874,  1.08992674,  0.88586228],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962],
       [-1.41529408, -0.71560577,  1.2651924 , -0.94210196],
       [-1.96300764,  0.70733253,  0.71089796, -0.30648372]])

In [45]:
mask = (name == 'Bob') | (name == 'Will')

In [46]:
mask

array([ True, False,  True,  True,  True, False, False])

In [47]:
name

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
data[mask]

array([[ 0.11792867,  0.5669166 , -0.37619867, -0.71531847],
       [ 0.80985535,  0.17013103,  2.07143869, -0.89926317],
       [ 0.33188533, -1.63265133,  0.01618467, -0.83990496],
       [ 0.49961471,  0.2573864 , -0.88082457, -1.80174962]])

In [50]:
data<0

array([[False, False,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True]])

In [51]:
data[data<0]

array([-0.37619867, -0.71531847, -0.89926317, -1.63265133, -0.83990496,
       -0.88082457, -1.80174962, -1.41529408, -0.71560577, -0.94210196,
       -1.96300764, -0.30648372])

In [52]:
data[data<0] = 0

In [53]:
data

array([[0.11792867, 0.5669166 , 0.        , 0.        ],
       [0.35090495, 0.58773874, 1.08992674, 0.88586228],
       [0.80985535, 0.17013103, 2.07143869, 0.        ],
       [0.33188533, 0.        , 0.01618467, 0.        ],
       [0.49961471, 0.2573864 , 0.        , 0.        ],
       [0.        , 0.        , 1.2651924 , 0.        ],
       [0.        , 0.70733253, 0.71089796, 0.        ]])

# Fancy Indexing

In [56]:
arr = np.empty ((8,4))

In [57]:
arr

array([[0.06869587, 1.88694885, 1.26019389, 0.92377876],
       [0.02741256, 0.41630597, 0.16719153, 1.30334476],
       [0.88685102, 0.34657757, 1.57150019, 0.56095224],
       [1.66935397, 2.90301721, 0.32662794, 1.01353827],
       [0.59513662, 0.56041875, 1.29290814, 1.12162791],
       [0.92355452, 1.22753216, 1.78813932, 0.96014568],
       [0.30460384, 1.81756463, 1.43387914, 0.80774468],
       [0.7545871 , 1.72717354, 0.01422106, 1.16338953]])

In [61]:
for i in range(8):
    arr[i]= i

In [62]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
arr[4]

array([4., 4., 4., 4.])

In [64]:
arr[[4,3,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [66]:
arr[4,2:]

array([4., 4.])

In [67]:
arr[[4,6],2:]

array([[4., 4.],
       [6., 6.]])

In [74]:
arr = np.arange(32).reshape((8,4))

In [75]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [78]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Array Transpose and Swapping Axes

In [79]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

# Array Oriented Programing with Arrays

In [80]:
  arr = np.arange(24)

In [81]:
arr.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [96]:
np.ravel(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])