In [2]:
import numpy as np

In [9]:
arr3d = np.arange(50).reshape(2,5,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [10]:
arr3d[1,2,3]

38

In [11]:
arr3d[0,3,4]

19

In [16]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [18]:
arr3d[0,2:,4] #oneDimension

array([14, 19, 24])

In [19]:
arr3d[0,2:4,4]

array([14, 19])

In [20]:
arr3d[0:1,2,3:] #twoDimension

array([[13, 14]])

In [22]:
arr3d[0:1,2:4,3:] #threeDimension

array([[[13, 14],
        [18, 19]]])

In [24]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [25]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

In [26]:
from pandas import Series, DataFrame

In [27]:
import pandas as pd

In [31]:
obj = pd.Series([10,11,12,13])

In [32]:
obj #Left side is auto index. obj(index,value)

0    10
1    11
2    12
3    13
dtype: int64

In [33]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [35]:
obj.values

array([10, 11, 12, 13], dtype=int64)

In [36]:
obj1 = pd.Series([13,25,56,85], index = ['a', 'b', 'c', 'd'])

In [37]:
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [44]:
obj1['d']

85

In [45]:
obj1['c']=100

In [46]:
obj1['c']

100

In [47]:
obj1

a     13
b     25
c    100
d     85
dtype: int64

In [48]:
del obj1['c']

In [49]:
obj1

a    13
b    25
d    85
dtype: int64

In [51]:
obj1['z'] = 250

In [52]:
obj1

a     13
b     25
d     85
z    250
dtype: int64

In [55]:
index = [1,2,3,4,5]

In [56]:
obj2 = pd.Series(["apple", "orange", "Red", "Green", "Blue"], index=index)

In [57]:
obj2

1     apple
2    orange
3       Red
4     Green
5      Blue
dtype: object

In [58]:
obj2[4]

'Green'

In [59]:
obj2[2]

'orange'

In [60]:
obj2[[3,5,1]]

3      Red
5     Blue
1    apple
dtype: object

In [62]:
obj2[obj2=='banana']

Series([], dtype: object)

In [64]:
obj2[obj2=='Red']

3    Red
dtype: object

In [66]:
obj2*2

1      appleapple
2    orangeorange
3          RedRed
4      GreenGreen
5        BlueBlue
dtype: object

In [68]:
print("apple "*5)

apple apple apple apple apple 


In [69]:
s1 = pd.Series([100,200,300,400,500], index=["H", "HH", "HHH", "HHHHH", "HHHHH"])

In [70]:
s1

H        100
HH       200
HHH      300
HHHHH    400
HHHHH    500
dtype: int64

In [72]:
'6h' in s1

False

In [74]:
'HH' in s1

True

In [80]:
data = {"Ohio": 4000, 'Texas': 5000, 'Oregon': 6000, 'Utah': 7000}

In [81]:
s2 = pd.Series(data)

In [82]:
s2

Ohio      4000
Texas     5000
Oregon    6000
Utah      7000
dtype: int64

In [83]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [86]:
s2 = pd.Series(data, index=states)

In [87]:
s2

California       NaN
Ohio          4000.0
Oregon        6000.0
Texas         5000.0
dtype: float64

In [88]:
pd.isnull(s2)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [90]:
s2[pd.isnull]

California   NaN
dtype: float64

In [91]:
data = {'state': ["Ohio", "Ohio", "Ohio","Nevada", "Nevada", "Nevada"],
       'year' : [2000,2001,2002,2001,2002,20003],
        'pop' :[1.5,1.7,3.6,2.4,2.9,3.2]
       }

In [94]:
df = pd.DataFrame(data)

In [95]:
df

state   year  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio   2002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9
5  Nevada  20003  3.2

In [101]:
df.tail(2)

state   year  pop
4  Nevada   2002  2.9
5  Nevada  20003  3.2

In [100]:
df.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
state    6 non-null object
year     6 non-null int64
pop      6 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


In [104]:
df.describe()

year       pop
count      6.000000  6.000000
mean    5001.500000  2.550000
std     7349.204113  0.836062
min     2000.000000  1.500000
25%     2001.000000  1.875000
50%     2001.500000  2.650000
75%     2002.000000  3.125000
max    20003.000000  3.600000

In [106]:
df.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [109]:
pd.DataFrame(df,columns=['year','state','pop'])

year   state  pop
0   2000    Ohio  1.5
1   2001    Ohio  1.7
2   2002    Ohio  3.6
3   2001  Nevada  2.4
4   2002  Nevada  2.9
5  20003  Nevada  3.2

In [124]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two','three','four','five','six'])

In [125]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
six    20003  Nevada  3.2  NaN

In [126]:
frame2.year

one       2000
two       2001
three     2002
four      2001
five      2002
six      20003
Name: year, dtype: int64

In [132]:
frame2.debt = range(6)

In [133]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5     0
two     2001    Ohio  1.7     1
three   2002    Ohio  3.6     2
four    2001  Nevada  2.4     3
five    2002  Nevada  2.9     4
six    20003  Nevada  3.2     5

In [134]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [135]:
frame2.year

one       2000
two       2001
three     2002
four      2001
five      2002
six      20003
Name: year, dtype: int64

In [136]:
frame2[['state','year']]

state   year
one      Ohio   2000
two      Ohio   2001
three    Ohio   2002
four   Nevada   2001
five   Nevada   2002
six    Nevada  20003

In [137]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt        2
Name: three, dtype: object

In [138]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt        2
Name: three, dtype: object

In [144]:
val = pd.Series([111,222,333],index=['one','four','three'])

In [145]:
frame2.debt=val

In [146]:
frame2

year   state  pop   debt
one     2000    Ohio  1.5  111.0
two     2001    Ohio  1.7    NaN
three   2002    Ohio  3.6  333.0
four    2001  Nevada  2.4  222.0
five    2002  Nevada  2.9    NaN
six    20003  Nevada  3.2    NaN

In [147]:
frame2['eastern']= frame2.state =='Ohio'

In [148]:
frame2

year   state  pop   debt  eastern
one     2000    Ohio  1.5  111.0     True
two     2001    Ohio  1.7    NaN     True
three   2002    Ohio  3.6  333.0     True
four    2001  Nevada  2.4  222.0    False
five    2002  Nevada  2.9    NaN    False
six    20003  Nevada  3.2    NaN    False